import { Link } from 'react-router-dom';
import Reveal from '../components/Reveal.jsx';
import { expertise, insights } from '../content.js';

export default function Home() {
  return <>
    <section className="px-[5vw] py-16 md:py-28"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow">E-commerce decision support</p><h1 className="display mt-6 max-w-5xl">A clearer view of the decision in front of your business.</h1><div className="mt-10 grid max-w-3xl gap-6 md:grid-cols-[1fr_auto] md:items-end"><p className="text-xl leading-8 text-[#4c4942]">Sind &amp; Sind helps founders and operators turn complicated commercial questions into practical next steps.</p><Link to="/consultant" className="button-primary">Try the free consultant <span>↗</span></Link></div></Reveal></div></section>
    <section className="border-y border-[#d6d1c3] bg-[#efebe1] px-[5vw] py-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><Reveal><p className="eyebrow">Start with the question</p><p className="mt-4 text-lg leading-7">Advertising, conversion, pricing, inventory, marketplaces or returns.</p></Reveal><Reveal><p className="eyebrow">Work from the economics</p><p className="mt-4 text-lg leading-7">Examine the constraint before choosing a tactic.</p></Reveal><Reveal><p className="eyebrow">Take one useful next step</p><p className="mt-4 text-lg leading-7">Use a small, measurable test before a larger commitment.</p></Reveal></div></section>
    <section className="px-[5vw] py-20 md:py-28"><div className="mx-auto max-w-7xl"><Reveal><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Expertise</p><h2 className="section-title mt-4">Questions worth getting right.</h2></div><Link to="/expertise" className="text-sm underline underline-offset-4 hover:text-[#d8321e]">View all expertise</Link></div></Reveal><div className="mt-12 divide-y divide-[#d6d1c3] border-y border-[#d6d1c3]">{expertise.map((item) => <Reveal key={item.slug}><Link to={`/expertise/${item.slug}`} className="group grid gap-4 py-6 md:grid-cols-[90px_1.1fr_1fr] md:items-baseline"><span className="mono text-xs text-[#d8321e]">{item.number}</span><h3 className="text-2xl md:text-3xl">{item.title}</h3><p className="leading-6 text-[#625d54]">{item.summary}</p><span className="hidden text-right text-xl transition-transform group-hover:translate-x-1 md:block">↗</span></Link></Reveal>)}</div></div></section>
    <section className="bg-[#1b1914] px-[5vw] py-20 text-[#fffdf9]"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1.1fr_1fr]"><Reveal><p className="eyebrow text-[#e25b4c]">Free consultant</p><h2 className="section-title mt-4">A practical first pass, without a sales pitch.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#d6d1c3]">Describe your situation and receive a structured response from our local e-commerce playbook library. No account, no provider API, no hidden claim that it is human advice.</p><Link to="/consultant" className="button-light mt-8">Ask a question <span>↗</span></Link></Reveal><Reveal className="border-l border-[#5d5a53] pl-6 md:pl-10"><p className="mono text-xs tracking-[0.12em] text-[#e25b4c]">EXAMPLE QUESTION</p><p className="mt-5 text-2xl leading-9">“My supplier raised prices 20%. Do I raise prices too?”</p><p className="mt-8 border-l-2 border-[#d8321e] pl-4 leading-7 text-[#d6d1c3]">Begin with SKU-level contribution, then test whether price, bundles, negotiation or a mix of actions protects the customer proposition.</p></Reveal></div></section>
    <section className="px-[5vw] py-20 md:py-28"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow">Field notes</p><h2 className="section-title mt-4">Useful thinking, not generic content.</h2></Reveal><div className="mt-10 grid gap-6 md:grid-cols-3">{insights.map((item) => <Reveal key={item.title} className="h-full"><article className="h-full border border-[#d6d1c3] bg-[#fffdf9] p-6"><p className="mono text-xs uppercase tracking-[0.1em] text-[#d8321e]">{item.category}</p><h3 className="mt-8 text-2xl leading-8">{item.title}</h3><p className="mt-5 leading-6 text-[#625d54]">{item.excerpt}</p></article></Reveal>)}</div></div></section>
  </>;
}
